### ISSUE TITLE
"st" files are not copied to the output directory

### ISSUE THREAD

**Issue by SomeMaker** [K-Society/KSociety.SharpCubeProgrammer#125]
I tried to run the library in a WPF application, but got errors every time: 

- Error: Unable to list supported devices
- Error: Cannot identify the device

I also tried creating a console application and it worked. After comparing the output directories, I noticed that the WPF application did not have a "st" directory. I copied this directory from the console application and the WPF application worked just as well.

**Comment by maniglia** [comment]
Hello @SomeMaker 
Please can you provide me with some details about the WPF project such as target framework and platform.
Thank you.

**Comment by SomeMaker** [comment]
NET Framework 4.8 Any CPU

**Comment by maniglia** [comment]
Hello @SomeMaker 
I released a new version ([v0.2.59](https://www.nuget.org/packages/KSociety.SharpCubeProgrammer)).

### ⚠ BREAKING CHANGES

The new version is not completely backwards compatible, there are some breaking chnages.
If you find it difficult, please consult the [examples](https://github.com/K-Society/KSociety.SharpCubeProgrammer/blob/master/src/01/Samples/QuickStart/Program.cs).
Please let me know if the problem is gone using the new version.
Regards

**Comment by SomeMaker** [comment]
The new version (0.2.59) still has the problem. 
Maybe the following information will help you, to reproduce the problem.
Microsoft Visual Studio Community 2022 (64-bit version) - Current Version 17.7.3.

Console application. I create a new console application project, install the KSociety.SharpCubeProgrammer package. Start the build. The output directory contains the "st" directory. Target platform NET 6.0 Any CPU.

WPF application. I create a new WPF application project, install the KSociety.SharpCubeProgrammer package. Start the build. There is no "st" directory in the output directory. .NET Framework 4.8 Any CPU. 

![image](https://github.com/K-Society/KSociety.SharpCubeProgrammer/assets/36761420/7bf859be-2cad-4c4a-9d6a-38541766b4be)

**Comment by SomeMaker** [comment]
https://github.com/SomeMaker/TestWpfProject/tree/master

**Comment by maniglia** [comment]
If you can, please use _PackageReference_.
You can easily migrate from _packages.config_ to _PackageReference_ using the **Migrate packages.config to PackageReference...** option in the drop-down menu by clicking the right mouse button on the _References_ node of the project.
