### ISSUE TITLE
Output folder ST is missing

### ISSUE THREAD

**Issue by Jannebozz** [K-Society/KSociety.SharpCubeProgrammer#137]
Installed it using nuget but when running and trying to connect using `ConnectDfuBootloader`, i get the following;
Seems like it can´t find the database. Do you need to copy this manually?

Message: STM32CubeProgrammer API v2.16.0 | Windows-64Bits 
Message: Device Descriptor:
Message:                         |_bLength                : 0x12
Message:                         |_bDescriptorType        : 0x01
Message:                         |_bcdUSB                 : 0x0100
Message:                         |_bDeviceClass           : 0x00
Message:                         |_bDeviceSubClass        : 0x00
Message:                         |_bDeviceProtocol        : 0x00
Message:                         |_bMaxPacketSize         : 0x40
Message:                         |_idVendor               : 0x0483
Message:                         |_idProduct              : 0xdf11
Message:                         |_bcdDevice              : 0x2200
Message:                         |_iManufacturer          : 0x01
Message:                         |_iProduct               : 0x02
Message:                         |_iSerialNumber          : 0x03
Message:                         |_bNumConfigurations     : 0x01
Message: Configuration Descriptor:
Message:                         |_bLength                : 0x09
Message:                         |_bDescriptorType        : 0x02
Message:                         |_wTotalLength           : 0x2d
Message:                         |_bNumInterfaces         : 0x01
Message:                         |_bConfigurationValue    : 0x01
Message:                         |_iConfiguration         : 0x00
Message:                         |_bmAttributes           : 0xc0
Message:                         |_bMaxPower              : 0x32
Message: Interface Descriptor Alternate Settings: 0x00
Message:                         |_bLength                : 0x09
Message:                         |_bDescriptorType        : 0x04
Message:                         |_bInterfaceNumber       : 0x00
Message:                         |_bAlternateSetting      : 0x00
Message:                         |_bNumEndpoints          : 0x00
Message:                         |_bInterfaceClass        : 0xfe
Message:                         |_bInterfaceSubClass     : 0x01
Message:                         |_bInterfaceProtocol     : 0x02
Message:                         |_iInterface             : 0x04
Message: Interface Descriptor Alternate Settings: 0x01
Message:                         |_bLength                : 0x09
Message:                         |_bDescriptorType        : 0x04
Message:                         |_bInterfaceNumber       : 0x00
Message:                         |_bAlternateSetting      : 0x01
Message:                         |_bNumEndpoints          : 0x00
Message:                         |_bInterfaceClass        : 0xfe
Message:                         |_bInterfaceSubClass     : 0x01
Message:                         |_bInterfaceProtocol     : 0x02
Message:                         |_iInterface             : 0x05
Message: Interface Descriptor Alternate Settings: 0x02
Message:                         |_bLength                : 0x09
Message:                         |_bDescriptorType        : 0x04
Message:                         |_bInterfaceNumber       : 0x00
Message:                         |_bAlternateSetting      : 0x02
Message:                         |_bNumEndpoints          : 0x00
Message:                         |_bInterfaceClass        : 0xfe
Message:                         |_bInterfaceSubClass     : 0x01
Message:                         |_bInterfaceProtocol     : 0x02
Message:                         |_iInterface             : 0x06
Message: Functional Descriptor :
Message:                         |_bLength                : 0x09
Message:                         |_bDescriptorType        : 0x21
Message:                         |_bmAttributes           : 0x0b
Message:                         |_wDetachTimeOut         : 0xff
Message:                         |_wTransferSize          : 0x0800
Message:                         |_bcdDFUVersion          : 0x011a
Message: USB speed   : Full Speed (12MBit/s)
Message: Manuf. ID   : STMicroelectronics
Message: Product ID  : STM32  BOOTLOADER
Message: SN          : 044732410000
Message: DFU protocol: 1.1
Message: Board       : --
Message: Device ID   : 0x0447
Message: DFU status = 0 : OK
Message: DFU state = 9  : dfuUPLOAD-IDLE
Message: Status: 0, State: 9
Message: sending an abort request
Message: DFU status = 0 : OK
Message: DFU state = 2  : dfuIDLE
Message: setting the address pointer to address: 0x08000000
Message: data: 2100000008
Message: DFU status = 0 : OK
Message: DFU state = 4  : dfuDNBUSY
Message: DFU status = 0 : OK
Message: DFU state = 5  : dfuDNLOAD-IDLE
Message: data: 2100000008
Message: Error: Database cannot be found. DatabasePath = ./st/Programmer/../Data_Base/STM32_Prog_DB_0x447.xml
Message: DFU status = 0 : OK
Message: DFU state = 9  : dfuUPLOAD-IDLE
Message: Status: 0, State: 9
Message: sending an abort request
Message: DFU status = 0 : OK
Message: DFU state = 2  : dfuIDLE
Message: setting the address pointer to address: 0x08000000
Message: data: 2100000008
Message: DFU status = 0 : OK
Message: DFU state = 4  : dfuDNBUSY
Message: DFU status = 0 : OK
Message: DFU state = 5  : dfuDNLOAD-IDLE
Message: data: 2100000008
Message: Error: CUBEPROGRAMMER_ERROR_NOT_SUPPORTED
Message: Disconnected from device.

Thanks for a nice implementation!

**Comment by maniglia** [comment]
Hello @Jannebozz 
Thank you for opening this issue.
Are you using the _PackageReference_?

**Comment by Jannebozz** [comment]
Hi, Not really sure so most likely not :) 
Need to look into how to do that...

**Comment by maniglia** [comment]
[Here](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference) you can find some useful information.

**Comment by Jannebozz** [comment]
So, migrated the project to PackageReference.
.csproj file now includes
```
<ItemGroup>
    <PackageReference Include="KSociety.SharpCubeProgrammer">
      <Version>0.3.9</Version>
    </PackageReference>
  </ItemGroup>
```
But still can´t get it to put out the data base

**Comment by maniglia** [comment]
Please try deleting the contents of the _obj_ folder and then compile the project again.
It must work!

**Comment by Jannebozz** [comment]
Cleaned everything and that helped...
thanks!
