### ISSUE TITLE
Wrong Parameter when Connecting

### ISSUE THREAD

**Issue by shaggygi** [K-Society/KSociety.SharpCubeProgrammer#52]
Recently came across this project.  Very interesting and good job.  I currently have STM32CubeProgrammer v2.14.0 installed and receive "wrong parameter" error when trying to connect to my board using the sample app.  Have you seen related errors?

It will connect calling the `connectStLink` function using the examples provided within the STM32 install.

Thx in advance.

**Comment by maniglia** [comment]
Hello @shaggygi,
thanks for your feedback.

1. Please make sure you have updated the firmware of your ST-LINK V2 / V3, you can do this using STM32CubeProgrammer.

2. The `ConnectStLink` method requires the data structure: `DebugConnectParameters` (the `stLink` variable in my example).
I think you can try changing some data structure parameter before calling `ConnectStLink`.


![SharpCubeProgrammer](https://github.com/K-Society/KSociety.SharpCubeProgrammer/assets/46456583/42b21814-19f8-4583-88f2-7743836d70a0)

Please try playing with the `DebugConnectParameters` parameters and let me know if you can connect with your device.

Regards.

**Comment by maniglia** [comment]
Sorry, I reread your question better.
When you say:

> It will connect calling the connectStLink function using the examples provided within the STM32 install.

You are referring to the STM32CubeProgrammer project, the `STM32CubePrgAPI.vcxproj`.
There seems to be a bug...

But I need more details to help you, can you share your example project which generates the problem?

**Comment by shaggygi** [comment]
Hi @maniglia.  I was going to attempt to update the firmware in my programmer as you mentioned.  And while on my drive home tonight, I realized it's not the programmer as I mentioned I was able to connect using the provided examples by ST.  Yes, I can compile and run all the examples that are included with their download.  Therefore, it doesn't appear to be the programmer firmware (but not sure).

To give some context, I too was creating a STM32 C# wrapper and was having similar issues.  While my code was not as detailed as your code yet, they have similarities.  I also got the "wrong parameters" (-8) error code when calling the connectStLink function.  This is the same as I'm seeing using your project example.

If needed, I can try to provide you with more screenshots/data later this week.  However, I basically downloaded your project and stepped through the code getting the same error.  No other code was added and tried with 2 different Nucleo boards.

![image](https://github.com/K-Society/KSociety.SharpCubeProgrammer/assets/2956825/490e72f5-4a65-442a-99ee-659a6233a627)

![image](https://github.com/K-Society/KSociety.SharpCubeProgrammer/assets/2956825/1a9e346d-2de4-47e4-8f4a-b03fe72fd20f)

I believe downloaded the x86 version of STM32CubeProgrammer, but appears your project includes both x86/x64.  I've only tried the x86 version so far.

I compared the variables returned from the C# wrapper versus the C++ example and all appear to be consistent except for `Speed`.  I've not understood why that would be different and I've tried updating to different values before connecting and still get the same "Wrong Parameter" error. 🤔

Let me know how I can help and thanks again for your response/review.

**Comment by shaggygi** [comment]
Right after I sent this, I noticed we have different firmware versions.

Yours: V2J42S7
Mine: V2J42M27

This could be the issue.  I tried performing the update and get a "proxy settings" prompt.  Doesn't appear I can make a connection.  I also came across the link below where others are having similar issues.

https://community.st.com/t5/stm32cubeprogrammer-mcus/cubeprogrammer-software-update-does-not-work/td-p/576605

Regarding the `Speed` differences above... it appears the `Speed` property was added in the recent programmer version.  The differences I'm seeing when reading might just be a pointer looking at the next memory.

If you have an idea on getting the proxy to work, this might be solution to my original problem.  Thx

**Comment by maniglia** [comment]
I was able to reproduce the same error as yours.
Please try compiling the example using the `x64` setting, there is a bug in the `x86` version.
Your firmware version is correct, but in any case, you can try updating the firmware from here:
![SharpCubeProgrammer2](https://github.com/K-Society/KSociety.SharpCubeProgrammer/assets/46456583/14a8f77d-b707-4ba9-a9e1-eab0aee4c74f)

I have never used the STM32CubeProgrammer software update, and consequently I never used the proxy server.

**Comment by shaggygi** [comment]
I will attempt the x64 version as you mentioned tonight.  That should keep me going if it works, but sadly will eventually need the x86 version due to some limitation I plan to use.

Do you think this is a bug with the ST firmware/API or related to how it is being used with the wrapper?  If it is a ST bug, how would you go about informing them it might be something they should review/address?

Thx

**Comment by maniglia** [comment]
I think it's a wrapper problem, I have to investigate a little deeper.

**Comment by shaggygi** [comment]
I had some time to try the x64 version and appears to have issues, as well.  I'm not sure if it is my environment or something else, but did need to modify a few things to make progress.  For example...

The original DLL name had to be updated from Programmer.dll to CubeProgrammer_API.dll.

![image](https://github.com/K-Society/KSociety.SharpCubeProgrammer/assets/2956825/8aa1acfe-5b2a-4eca-8cb6-18c64f0ced06)

Many of the native EntryPoints had to be updated where they were capitalized.  For example...

- GetStLinkList -> getStLinkList
- Disconnect -> disconnect
- ConnectStLink -> connectStLink

After above was updated, the exceptions went away but now get a -545 error code returned from API.

![image](https://github.com/K-Society/KSociety.SharpCubeProgrammer/assets/2956825/079cb549-f02f-4164-8889-50360550e283)

Hope this helps narrow down anything.  Thx

**Comment by maniglia** [comment]
Thanks for taking the time to try to figure out where the problem is.
But let me explain how this project is structured:
The CubeProgrammer_API.dll is not called directly from C#, but is used by a Programmer.dll library.
The Programmer.dll library handles some tedious logging functions, and is used as middleware between CubeProgrammer_API and C#.
The Programmer.dll library is very stupid, it is dummy, for example:
`int ConnectStLink(debugConnectParameters debugParameters) 
{
	return connectStLink(debugParameters);
}`

_connectStLink(debugParameters)_ is the call to the CubeProgrammer_API library function while _ConnectStLink(debugConnectParameters debugParameters)_ is used in C#.

I think the problem in this case is linked to how the data structure `DebugConnectParameters` is translated from the different platforms (x64 and x86).
I think it's a marshalling problem, but I'm not sure, the `DebugConnectParameters` structure it's very complicated.

As an alternative solution I can introduce a new function in the Programmer.dll library, the `TryConnectStLink` function which internally calls both the `getStLinkList` function and the `connectStLink` function without having to manage the `debugConnectParameters` data structure in C#.

**Comment by shaggygi** [comment]
👍ok.  let me know when you have some new bits and i'll try them out.  thx.

**Comment by maniglia** [comment]
I found and solved the problem with the `getStLinkList` function.
I did some tests on both x64 and x86 and it seems to work well, I hope I haven't introduced any other problems.
In the end the `DebugConnectParameters` data structure is correct.
Thanks

**Comment by shaggygi** [comment]
Thanks for response.  I just got latest and tried again with same issue with a returned -545 when calling ConnectStLink.  I also understand your setup with the middleware API, but still get errors unless I rename DLL and EntryPoints as described before.  I could be doing something wrong, but assume you should be able to set the Samples > Programming as starting project and hit F5 to run (with no modifications).

Could the connection issue be caused by having wrong .NET Core runtime installed?  I've tried using x86, x64, and also created a .NET 4.8 (full framework) Console project with same results.  Again, tried on 2 different boards.  Thx

**Comment by maniglia** [comment]
Try closing Visual Studio and deleting the contents of the obj and bin folders and then trying again; open Visual Studio, compile the project and run it.
For the Programming project, do not use the project reference to SharpCubeProgrammer, use the Nuget package.
I just tried it again and it worked.

**Comment by shaggygi** [comment]
OK, I created a completely separate solution/project and referenced the latest NuGet and now appears to work.  I'll try tinkering around to see what I was doing wrong within the main solution.

Again, thanks for all the help on my issue.  👍
